### ISSUE TITLE
Improve notification management

### ISSUE THREAD

**Issue by Helghardt** [rehive/dashboard#2]
1. Can you configure global notification preference for both email or mobile individually, or does this apply to both.
2. Look at Notifactions and Controls - the format is not consistent. For Notifications the first letter is a capital for each word. For Controls we mostly use smaller case letter, expect for the first word. Let's choose a consistent format.

![image](https://cloud.githubusercontent.com/assets/5997897/19820873/3039e52a-9d10-11e6-9c77-1d63d6befb29.png)

**Comment by OdinsPlasmaRifle** [comment]
1) Each checkbox applies to both email and SMS(it is a way to globally disable messages for a specific type of notification rather than the method used to send notifications). I don't think it makes sense that an admin gets to choose where a user gets their notifications (on their phone or in their inbox). And I don't think there are many cases where such a feature would be useful especially as a user might have ONLY a mobile number or ONLY an email address, which would introduce a lot of problems into the equation.

2) I have improved the consistency and opted for a capitalized first letter and lower case for all subsequent words in the control/limit/notification descriptions.
